### ISSUE TITLE
请问在prerender-spa-plugin怎么替换puppeteer

### ISSUE THREAD

**Issue by dolphinfine** [valleykid/puppeteer-cn#6]
这个预渲染的插件
https://github.com/chrisvfritz/prerender-spa-plugin
并没有直接暴露出来哪里使用了puppeteer
这种情况下怎么使用puppeteer-cn？

**Comment by valleykid** [comment]
我看了下它们的依赖链是：prerender-spa-plugin 依赖了 @prerenderer/renderer-puppeteer，而后者依赖了 puppeteer。要不你把这两个模块都 fork 一份，改完依赖后发布新模块到 npm？

**Comment by dolphinfine** [comment]
谢谢了。我直接用cnpm安装了，不搞那么麻烦。
