### ISSUE TITLE
貌似不支持linux？

### ISSUE THREAD

**Issue by Kelier** [valleykid/puppeteer-cn#7]
ubuntu上装过之后，调用我的js发生了错误

报的错误提示找不到puppeteer模块

而mac是可以的

**Comment by valleykid** [comment]
我在 gcp 上使用是正常的啊，系统是 debian。要不你删除 node_modules 重新安装下~

**Comment by cewin** [comment]
> ubuntu上装过之后，调用我的js发生了错误
> 
> 报的错误提示找不到puppeteer模块
> 
> 而mac是可以的

我的本地运行正常，放在centos7上显示Chromium revision is not downloaded.

**Comment by valleykid** [comment]
@cewin 是不是 Chromium 运行所需要的依赖项没有安装呢？参考下这个 https://github.com/GoogleChrome/puppeteer/issues/290#issuecomment-451471338

**Comment by Kelier** [comment]
即使编译安装了还是有问题，我试过了

**Comment by Kelier** [comment]
当然了，我的是centos6.3，基本无解
