### ISSUE TITLE
page.waitForSelector timeout

### ISSUE THREAD

**Issue by Xbantian** [valleykid/puppeteer-cn#8]
你好，循环了多次（100次左右）goto页面后，再调page.waitForSelector总会超时。看了下官方应该解决这个问题了
TimeoutError: waiting for selector ".code.highlight" failed: timeout 1000ms exceeded\n    at new WaitTask (..\node_modules\puppeteer-cn\node_modules\puppeteer\lib\DOMWorld.js:554:28)

**Comment by valleykid** [comment]
能否贴一下复现的 demo 或代码出来，方便我查找下原因~
